### ISSUE TITLE
Problem reading default lang folder path

### ISSUE THREAD

**Issue by vukasinovic** [kg-bot/laravel-localization-to-vue#35]
In v1.5.5 there is a problem reading default **resources/lang** folder.
To fix this I needed to change laravel-localization.php on line 92
 from `: ['resources/lang'],` to `: [resource_path('lang')],` 
As this returns relative path and first one couldn't find lang folder.
Please fix that

**Comment by nafizcayli** [comment]
I am having the exact same issue. The thrown exception message is:

`Can't read lang directory resources/lang, error: RecursiveDirectoryIterator::__construct(resources/lang): failed to open dir: No such file or directory`

I published the config file, and made the change @vukasinovic suggested. Now it is working fine. 
Thanks for the package @kg-bot !

**Comment by nafizcayli** [comment]
I just followed your directions.
But when i try to use it with ViewComposer, 

```php
View::composer( 'view.file', function ( $view ) {
    return $view->with( [
        'messages' => ExportLocalization::export()->toArray(),
    ]);
});
```
it just returns an empty array. (Because of the exception that i mentioned earlier.)

FYI: When i was debugging the problem, i realized that when i run the command `ExportLocalization::export()->toArray()` inside a `tinker` session, it works without an issue.
